/**
 * Exception during resolution should be wrapped and re-thrown.
 */
@Test
public void testGetType06() {
    doThrowableTest(TesterBeanNameResolver.EXCEPTION_TRIGGER_NAME, MethodUnderTest.GET_TYPE);
}