/*
     * This is also tested implicitly in numerous places elsewhere in this
     * class.
     */
@Test
public void testBug49655() throws Exception {
    // This is the call the failed
    MethodExpression me = factory.createMethodExpression(context, "#{beanA.setName('New value')}", null, null);
    // The rest is to check it worked correctly
    me.invoke(context, null);
    ValueExpression ve = factory.createValueExpression(context, "#{beanA.name}", java.lang.String.class);
    Assert.assertEquals("New value", ve.getValue(context));
}